Minecraft 1.21.3 update
sf-inc/music_control pull request #68
Opened 2024-11-16 22:43 UTC by FlailoftheLord

**Commit**: https://github.com/sf-inc/music_control/commit/0f858226a281ac2f3787b8b7c548f0a0a21308a3

Updating Mappings `gradle.properties` for Minecraft 1.21.3 to  the following values:
```properties
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.9

# Fabric API
fabric_version=0.108.0+1.21.3
```
`SoundEvent` Registry `#getId` changed to `#id` refferences in the following (3) files have been changed.
 - `src/main/java/com/github/charlyb01/music_control/categories/MusicIdentifier.java` 
 - `src/main/java/com/github/charlyb01/music_control/categories/MusicCategories.java`
 - `src/main/java/com/github/charlyb01/music_control/mixin/MusicTrackerMixin.java`

Method `#isFallFlying` no longer exists; has been replaced with `#isGliding` in class `MusicIdentifier.java`

`BiomeKeysMixin`  `BiomeKeys` refference changed from `#register` to `#keyOf`
`WorldRenderMixin` no longer needed for Jukebox display. `src/main/resources/music_control.mixins.json`

2024-11-19 07:44 UTC, charlyb01 commented
Hi, thanks for the PR. I'll take a look at it during the week, I'll let you know then if it's all good for me

2024-11-19 17:15 UTC, charlyb01 requested changes
I'm gonna do a test to check everything's working. Not that I don't trust you, just that I'm aware of some things that can be tricky to spot. The overall seems good to me, it seems there were not many changes impacting this mod in this new minecraft version, cool!

Please just keep the structure of the `gradle.properties` as it was. If you know how, feel free to fixup the change in your first commit to avoid useless commits, otherwise that's not a big deal.

Thanks again for your work 🙂

2024-11-19 17:15 UTC, charlyb01 commented on gradle.properties
> +org.gradle.jvmargs=-Xmx2048M
This changed is unnecessary, one mod doesn't require this much RAM

2024-11-19 17:15 UTC, charlyb01 commented on gradle.properties
> +fabric_version=0.108.0+1.21.3
Please keep it with mod dependencies, as this is a mod dependency. No need to treat the Fabric API differently

2024-11-19 17:15 UTC, charlyb01 commented on gradle.properties
> +
Just like the new fabric section, I'd like to keep the section as they were

2024-11-21 14:06 UTC, FlailoftheLord commented
Yeah, I just pasted the info from the fabric dev website to get the dependencies working... completely forgot about the ram change too lol

2024-11-21 21:11 UTC, charlyb01 approved these changes
Perfect, thanks! 🙂

2024-11-21 21:11 UTC, merged

2024-11-21 21:22 UTC, charlyb01 commented on src/main/java/com/github/charlyb01/music_control/mixin/WorldRendererMixin.java
Damn it, I knew I should have put a comment there... I forgot to check it during my test, so I merged it, but this is still necessary as I expected. I'll do the fix, no worries

2024-11-22 15:20 UTC, FlailoftheLord commented on src/main/java/com/github/charlyb01/music_control/mixin/WorldRendererMixin.java
wild, I couldn't figure out for the life of me what that class even did... I just ended up removing it because gradle refused to compile it.

2024-11-22 15:49 UTC, charlyb01 commented on src/main/java/com/github/charlyb01/music_control/mixin/WorldRendererMixin.java
This was to cancel the message print from the jukebox, as the comment suggested. This was useful because with the mod you can add multiple songs to a music disc, and by default, it would just print the name associated with the music disc, not the actual song name. And as you don't know the song before it's played (because the event chose a song randomly in it), then there you had no information of what music to display, so the print is made later in another mixin.

I'll fix it later today, I found where it's handled in the new version yesterday